version: "0.2"
words:
  - binstall
  - chrono
  - clippy
  - desaturate
  - msix
  - oneof
  - pubspec
  - reqwest
  - rinf
  - rustup
  - serde
  - startdate
  - temurin
  - thiserror
ignorePaths:
  - native/wallpaper
