version: "0.2"
words:
  - batchrsp
  - bindgen
  - binstall
  - bndy
  - cdylib
  - chrono
  - clippy
  - desaturate
  - msix
  - oneof
  - pubspec
  - reqwest
  - rinf
  - rustc
  - rustls
  - rustup
  - serde
  - startdate
  - staticlib
  - temurin
  - thiserror
  - Zoomable
ignorePaths:
  - native/wallpaper
